spring:
  application:
    name: cloud-gateway


hystrix:
  shareSecurityContext: false
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 30000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  eureka:
    enabled: true

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:

    product-service:
      path: /product/**
      serviceId: product-service
      stripPrefix: false
      retryable: true
      sensitiveHeaders:

    review-service:
      path: /review/**
      serviceId: review-service
      stripPrefix: false
      retryable: true
      sensitiveHeaders:




server:
  port: 4000

management:
  endpoints:
    web:
      exposure:
        include: routes, mappings
  endpoint:
     mappings:
       enabled: true
     routes:
       enabled: true

eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true

      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true

