spring:
  application:
    name: review-service

server:
  port: 8090
  servlet:
    context-path: /review


eureka:
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true